### ISSUE TITLE
portage-tui не робит в не-tty-терминале

### ISSUE THREAD

**Issue by mradermaxlol** [TyanNN/portage-tui#2]
Приветик.

Прога не работает в графических терминалах (пробовал в xfce-terminal, gnome-terminal и uxterm), curses выдаёт ошибку:
![2016-05-16 15-50-27](https://cloud.githubusercontent.com/assets/11138966/15289947/7d72dd1c-1b86-11e6-96ec-80529ec72432.png)

В tty всё путём. Вангую, что это баг модуля curses в питончике, хотя у меня всё было в порядке, когда сам писал с python3 + curses.

**Comment by vaartis** [comment]
Однако, в Guake работает

**Comment by pkulev** [comment]
Странно, у меня в uxterm работает. @mradermaxlol можешь перед 204 строкой принтами встать и проверить чему равно переменные, которые улетают в addwstr?

**Comment by vaartis** [comment]
@pkulev вообще, у меня такое было в Terminator'е, возможно, fish не передаёт размер терминала?

**Comment by pkulev** [comment]
Поставил fish, работает в roxterm и uxterm. Питон 2 и ресайзинг не работает, но если вечером останутся силы я их тебе запилю;)

**Comment by vaartis** [comment]
@pkulev потому что ресайзинга и не планировалось c: (лениво)

**Comment by pkulev** [comment]
Даже логиншелл поменял, работает.

**Comment by pkulev** [comment]
Кстати говоря, я запилил контейнер для данных, которые надо отдавать в таком виде в курсес. И поверх него мейнлуп. И ресайзинг работает и листать удобно, вниз вверх по позиции, а влево-вправо по страницам. Хочешь посмотреть код?

**Comment by vaartis** [comment]
@pkulev запили куда-нибудь, гляну, НАВЕРНОЕ.

**Comment by mradermaxlol** [comment]
> возможно, fish не передаёт размер терминала?

Таки дело не в фише.
![_2016-05-17_19-50-53](https://cloud.githubusercontent.com/assets/11138966/15331228/68549024-1c71-11e6-9438-40566fa2e062.png)

**Comment by vaartis** [comment]
@mradermaxlol ну чОрт. Такая ошибка бывает, когда пытаешься вставить строку в слишком маленькое окно. А размер окна получается от терминала. Почему-то у тебя терминалы не говорят свои размеры >_> У меня Terminator, например, их не говорит.

**Comment by mradermaxlol** [comment]
@TyanNN лул, говорят. Мб дело в хреновом коде получения размеров?
![_2016-05-17_20-11-58](https://cloud.githubusercontent.com/assets/11138966/15331810/1c1a7be4-1c74-11e6-9df7-4b19c4f01ce5.png)

**Comment by vaartis** [comment]
@mradermaxlol размеры получаются из curses.COLS и ROWS, нету там никакого кода для получения. В Terminator'е неожиданно заработало. Брауз, однако, не работает. Пороюсь с размерами, может ему места мало.

**Comment by TyanNN** [comment]
Забавно, он почему-то застревает на этой строке конкретно. Да на любой строке в принципе, добавленной туда.
